### ISSUE TITLE
starting with a losing deal

### ISSUE THREAD

**Issue by Jenna1337** [Nombril/CardGame#2]
The elevens game may sometimes start with a losing deal, adding to total games played.

**Comment by Jenna1337** [comment]
It appears that thirteens has this issue too, but a much smaller chance of it happening.

**Comment by Nombril** [comment]
Do you think we should change the program to prevent this?

Should it automatically redeal and still count it as a loss?

Or should it never be shown to the player?

**Comment by Jenna1337** [comment]
Fixed it. #3
